frontend:
  imagePullPolicy: Always
  image:
    name: 881299606849.dkr.ecr.us-east-1.amazonaws.com/chainlink-test-repo
    tag: client-new
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 300m
      memory: 400Mi
  service:
    name: chainlink
    port: 80

backend:
  imagePullPolicy: Always
  image:
    name: 881299606849.dkr.ecr.us-east-1.amazonaws.com/chainlink-test-repo
    tag: server-new-test
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 300m
      memory: 400Mi
  service:
    name: chainlink
    port: 3030
  secretName: db-secrets



