---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: {{ template "app.fullname" . }}
        image: {{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
        ports:
          - name: {{ template "app.fullname" . }}
            protocol: TCP
            containerPort: {{ .Values.frontend.service.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: {{ .Values.frontend.service.port }}
          timeoutSeconds: 5
        resources:
          requests:
            memory: {{ .Values.frontend.resources.requests.memory }}
            cpu: {{ .Values.frontend.resources.requests.cpu }}
          limits:
            memory: {{ .Values.frontend.resources.limits.memory }}
            cpu: {{ .Values.frontend.resources.limits.cpu }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: {{ template "app.fullname" . }}
        image: {{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
        ports:
          - name: {{ template "app.fullname" . }}
            protocol: TCP
            containerPort: {{ .Values.backend.service.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.backend.service.port }}
          initialDelaySeconds: 15
          timeoutSeconds: 15
        readinessProbe:
          tcpSocket:
            port: {{ .Values.backend.service.port }}
          timeoutSeconds: 15
        resources:
          requests:
            memory: {{ .Values.backend.resources.requests.memory }}
            cpu: {{ .Values.backend.resources.requests.cpu }}
          limits:
            memory: {{ .Values.backend.resources.limits.memory }}
            cpu: {{ .Values.backend.resources.limits.cpu }}
        envFrom:
          - secretRef:
              name: {{ .Values.backend.secretName }}
          