apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: {{ template "app.fullname" . }}-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.frontend.service.name }}-frontend
              servicePort: 80
