---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.frontend.service.name }}-frontend
spec:
  selector:
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.backend.service.name }}-backend
spec:
  selector:
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
