version: "3.3"

volumes: 
  pg_data:

services:
  client:
    build: 
      context: ./client
      args: [] 
      
    ports: 
      - 8080:80

    depends_on: 
      - server
    environment: 
      TYPEORM_HOST: db
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: postgres
      TYPEORM_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redispass
      PORT: 3030